using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace FitLife.Maui.ViewModels;

// ViewModel for the Settings page.
// Persists user preferences (language, notification toggles, location sharing)
// using MAUI Preferences — a key-value store backed by platform-native storage
// (SharedPreferences on Android, NSUserDefaults on iOS, Registry on Windows).
public partial class SettingsViewModel : BaseViewModel
{
    // Preference keys — stored as constants so they are consistent across the app
    private const string KeyLanguage        = "settings_language";
    private const string KeyNotifyWaitlist  = "settings_notify_waitlist";
    private const string KeyNotifyPush      = "settings_notify_push";
    private const string KeyNotifyCancelled = "settings_notify_cancelled";
    private const string KeyNotifyNews      = "settings_notify_news";
    private const string KeyLocationSharing = "settings_location_sharing";

    // Flag used to suppress Preferences.Set calls during the initial Load()
    // so that reading saved values doesn't trigger spurious writes or permission requests.
    private bool _isLoading = true;

    // Language selection (mutually exclusive radio buttons in the UI)
    [ObservableProperty] private bool _languageNl = true;
    [ObservableProperty] private bool _languageEn = false;

    // Notification preference toggles
    [ObservableProperty] private bool _notifyWaitlist;
    [ObservableProperty] private bool _notifyPush;
    [ObservableProperty] private bool _notifyCancelled;
    [ObservableProperty] private bool _notifyNews;

    // Location sharing toggle — triggers an OS permission request when turned on
    [ObservableProperty] private bool _locationSharing;

    public SettingsViewModel()
    {
        Title = "Instellingen";
        Load();          // restore previously saved values from device storage
        _isLoading = false;
    }

    // Reads all saved preferences from device storage and populates the observable properties.
    private void Load()
    {
        var lang   = Preferences.Get(KeyLanguage, "nl");
        LanguageNl = lang == "nl";
        LanguageEn = lang == "en";

        NotifyWaitlist  = Preferences.Get(KeyNotifyWaitlist,  true);
        NotifyPush      = Preferences.Get(KeyNotifyPush,      true);
        NotifyCancelled = Preferences.Get(KeyNotifyCancelled, true);
        NotifyNews      = Preferences.Get(KeyNotifyNews,      false);
        LocationSharing = Preferences.Get(KeyLocationSharing, false);
    }

    // Command bound to the language radio buttons — saves the chosen language code
    // and updates the mutual-exclusion flags.
    [RelayCommand]
    private void SelectLanguage(string lang)
    {
        LanguageNl = lang == "nl";
        LanguageEn = lang == "en";
        Preferences.Set(KeyLanguage, lang);

        // Switch the entire UI immediately — Translator notifies all
        // {Translate} bindings and updates the app culture.
        Services.Translator.Instance.SetLanguage(lang);
    }

    // These partial methods are auto-generated by CommunityToolkit.Mvvm and called
    // whenever the corresponding [ObservableProperty] value changes.
    // Each one immediately persists the new toggle state to device storage.
    partial void OnNotifyWaitlistChanged(bool value)  => Preferences.Set(KeyNotifyWaitlist,  value);
    partial void OnNotifyPushChanged(bool value)      => Preferences.Set(KeyNotifyPush,      value);
    partial void OnNotifyCancelledChanged(bool value) => Preferences.Set(KeyNotifyCancelled, value);
    partial void OnNotifyNewsChanged(bool value)      => Preferences.Set(KeyNotifyNews,      value);

    // When the user enables location sharing, request the OS permission.
    // If the permission is denied, revert the toggle to off.
    partial void OnLocationSharingChanged(bool value)
    {
        Preferences.Set(KeyLocationSharing, value);

        // Only request permission when the user actively turns the toggle on
        // (not during initial Load when _isLoading is true)
        if (value && !_isLoading)
            _ = RequestLocationPermissionAsync();
    }

    // Asks the OS for "location when in use" permission.
    // Reverts the toggle and saves false if the user denies access.
    private async Task RequestLocationPermissionAsync()
    {
        try
        {
            var status = await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>();

            // Only show the system dialog if not already granted
            if (status != PermissionStatus.Granted)
                status = await Permissions.RequestAsync<Permissions.LocationWhenInUse>();

            if (status != PermissionStatus.Granted)
            {
                // Permission denied — revert toggle and persist the disabled state
                LocationSharing = false;
                Preferences.Set(KeyLocationSharing, false);
            }
        }
        catch
        {
            LocationSharing = false;
            Preferences.Set(KeyLocationSharing, false);
        }
    }
}
