# docker compose file for local dev

services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: >
        Server=${DB_HOST};
        Port=${DB_PORT};
        Database=${DB_NAME};
        User=${DB_USER};
        Password=${DB_PASSWORD};
    depends_on:
      - db
    labels:
      - env=local
      - service=fitlife-api

  db:
    build:
      context: ./API/db
      dockerfile: Dockerfile
    image: fitlife-db:local
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - .env
    environment:
      PMA_HOST: ${PHP_MYADMIN_HOST}
      PMA_USER: ${DB_ROOT_USER}
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  mysql_data:
